"""
Builds/refreshes output/application_tracker.csv from scored_postings.json.

The tracker is a working document: some columns are generated by the
pipeline and refreshed on every run, others are yours to fill in and are
NEVER overwritten. Rows are matched by posting url, so you can edit in
Excel, re-run the pipeline, and keep your notes.

Usage:
  python build_tracker.py           # refresh the tracker
  python build_tracker.py --report  # also print a status summary
"""
import csv
import json
import sys
from datetime import date
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "output"
SCORED_PATH = OUTPUT_DIR / "scored_postings.json"
TRACKER_PATH = OUTPUT_DIR / "application_tracker.csv"

# refreshed from the pipeline on every run
GENERATED = ["score", "overqualified", "salary", "company", "title", "location",
             "source", "url", "resume", "cover_letter", "first_seen", "last_seen"]
# yours; never touched once written
USER = ["status", "date_submitted", "follow_up", "contact", "notes"]
FIELDS = GENERATED + USER

STATUS_VALUES = ("(blank)=not applied | applied | screening | interview | offer "
                 "| rejected | passed | closed=posting no longer listed")


def load_existing() -> dict:
    if not TRACKER_PATH.exists():
        return {}
    with open(TRACKER_PATH, newline="", encoding="utf-8-sig") as f:
        return {r["url"]: r for r in csv.DictReader(f) if r.get("url")}


def rel(path: str) -> str:
    """Store paths relative to the project root so the file stays portable."""
    if not path:
        return ""
    try:
        return str(Path(path).relative_to(OUTPUT_DIR.parent))
    except ValueError:
        return Path(path).name


def build(verbose: bool = True) -> list[dict]:
    scored = json.loads(SCORED_PATH.read_text(encoding="utf-8"))
    existing = load_existing()
    today = date.today().isoformat()

    rows, new_count = [], 0
    for e in scored:
        url = e.get("url", "")
        if not url:
            continue
        prior = existing.get(url, {})
        if not prior:
            new_count += 1

        row = {
            "score": e.get("score", ""),
            "overqualified": "yes" if e.get("overqualification_risk") else "",
            "salary": (f"${e['salary_low']//1000}K-${e['salary_high']//1000}K"
                       if e.get("salary_high") else ""),
            "company": e.get("company", ""),
            "title": e.get("title", "").strip(),
            "location": e.get("location", ""),
            "source": e.get("source", ""),
            "url": url,
            "resume": rel(e.get("tailored_resume_docx", "")),
            "cover_letter": rel(e.get("cover_letter_docx", "")),
            "first_seen": prior.get("first_seen") or today,
            "last_seen": today,
        }
        # carry your columns through untouched
        for col in USER:
            row[col] = prior.get(col, "")
        rows.append(row)

    # postings that have dropped off the boards: keep the row, flag it, so an
    # application you already sent doesn't silently vanish from the tracker
    current = {r["url"] for r in rows}
    for url, prior in existing.items():
        if url not in current:
            stale = {k: prior.get(k, "") for k in FIELDS}
            stale["url"] = url
            if not stale.get("notes", "").startswith("[no longer listed"):
                stale["notes"] = (f"[no longer listed as of {today}] " + stale.get("notes", "")).strip()
            rows.append(stale)

    def sort_key(r):
        try:
            score = -int(r["score"])
        except (ValueError, TypeError):
            score = 0
        return (score, r["company"].lower())

    rows.sort(key=sort_key)

    # Excel holds an exclusive lock on an open .csv. Don't lose the run --
    # write alongside it and say so loudly, since a nightly scheduled run
    # would otherwise skip the update every night the file is left open.
    target = TRACKER_PATH
    try:
        with open(target, "w", newline="", encoding="utf-8-sig") as f:
            w = csv.DictWriter(f, fieldnames=FIELDS)
            w.writeheader()
            w.writerows(rows)
    except PermissionError:
        target = TRACKER_PATH.with_suffix(".NEW.csv")
        with open(target, "w", newline="", encoding="utf-8-sig") as f:
            w = csv.DictWriter(f, fieldnames=FIELDS)
            w.writeheader()
            w.writerows(rows)
        print(f"  [TRACKER LOCKED] {TRACKER_PATH.name} is open in another program "
              f"(usually Excel).")
        print(f"  [TRACKER LOCKED] Wrote {target.name} instead. Close the file, "
              f"delete the old one, and rename this over it -- or just re-run "
              f"`python build_tracker.py`.")

    if verbose:
        applied = sum(1 for r in rows if r.get("date_submitted"))
        print(f"  tracker: {len(rows)} rows ({new_count} new, {applied} with a submit date)")
        # name what was actually written. Saying application_tracker.csv after
        # falling back to the .NEW.csv contradicts the warning above it, and
        # the summary is the line people read.
        print(f"  -> {target.name}   status values: {STATUS_VALUES}")
    return rows


def report(rows: list[dict]):
    print("\n" + "=" * 68)
    ready = [r for r in rows if r["resume"] and not r.get("date_submitted")
             and not r.get("notes", "").startswith("[no longer listed")]
    print(f"READY TO APPLY ({len(ready)}) -- documents drafted, no submit date yet:")
    for r in sorted(ready, key=lambda x: -int(x["score"] or 0)):
        flag = "  (overqualification risk)" if r["overqualified"] else ""
        print(f"   [{r['score']}/10] {r['company']} - {r['title'][:46]}{flag}")

    in_flight = [r for r in rows if r.get("date_submitted")]
    if in_flight:
        print(f"\nSUBMITTED ({len(in_flight)}):")
        for r in in_flight:
            print(f"   {r['date_submitted']}  {r['company']} - {r['title'][:40]}  [{r.get('status') or 'no status'}]")

    stale = [r for r in rows if r.get("notes", "").startswith("[no longer listed")]
    if stale:
        print(f"\nNO LONGER LISTED ({len(stale)}):")
        for r in stale:
            print(f"   {r['company']} - {r['title'][:46]}")


if __name__ == "__main__":
    rows = build()
    if "--report" in sys.argv:
        report(rows)
